### ISSUE TITLE
解压后没有启动脚本。。请问是怎么回事呢

### ISSUE THREAD

**Issue by solthx** [dwosc/RxTomcat#1]
mvn clean install 之后
在...../RxTomcat-master/rxtomcat-bootstrap/target/dist/rxtomcat-2.0.1-SNAPSHOT/bin/ 这个目录下只有一个bootstrap.jar。。没有rxtomcatd.sh。。 是什么原因呢。。

**Comment by wskwbog** [comment]
确实有这个问题，bin 下的脚本被 .gitignore 给过滤掉了，已经重新提交了。
